---

- name: local playbook
  hosts: localhost
  vars:
    terraform_version: 0.11.8
    packer_version: 1.3.1

  tasks:
  # comentado para ahorrar tiempo
  #- name: yum update all
  #  yum:
  #    name: '*'
  #    state: latest
  #  become: yes
  #  become_user: root
    
  - name: install requirements
    yum:
      name: 
       - unzip
       - docker
       - git
      state: present
    become: yes
    become_user: root
  
  - name: download terraform archive Linux 64 bits
    get_url:
      url: https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip
      dest: /tmp/terraform-{{terraform_version}}.zip
  
  - name: unarchive Terraform archive
    unarchive:
      src: /tmp/terraform-{{terraform_version}}.zip
      dest: /usr/local/bin/
      copy: no
    become: yes
    become_user: root
  
  - name: download packer archive Linux 64 bits
    get_url:
      url: https://releases.hashicorp.com/packer/{{ packer_version }}/packer_{{ packer_version }}_linux_amd64.zip
      dest: /tmp/packer-{{packer_version}}.zip
  
  - name: unarchive packer archive
    unarchive:
      src: /tmp/packer-{{packer_version}}.zip
      dest: /usr/local/bin/
      copy: no
    become: yes
    become_user: root
  
  - name: start docker engine
    service:
      name: docker
      state: started
    become: yes
    become_user: root
  